---
repos:
  - repo: local
    hooks:

      - id: pylint
        name: pylint
        entry: ./.venv/bin/pylint
        language: system
        types: [python]
        exclude: '^\.venv/'

      - id: autopep8
        name: autopep8
        entry: ./.venv/bin/autopep8
        language: system
        types: [python]
        args: [--aggressive, --aggressive, --in-place]
        exclude: '^\.venv/'

      - id: yamllint
        name: yamllint
        entry: ./.venv/bin/yamllint
        language: system
        types: [yaml]
        exclude: '^\.venv/'
